# Generated by Django 6.1.1 on 2026-09-16 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Veiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa', models.CharField(max_length=10, unique=True, verbose_name='Placa')),
                ('marca', models.CharField(blank=True, max_length=100, verbose_name='Marca')),
                ('modelo', models.CharField(blank=True, max_length=100, verbose_name='Modelo')),
                ('ano', models.IntegerField(blank=True, null=True, verbose_name='Ano')),
                ('cor', models.CharField(blank=True, max_length=50, verbose_name='Cor')),
                ('cliente', models.CharField(blank=True, max_length=150, verbose_name='Cliente')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Data de cadastro')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Data de atualização')),
            ],
            options={
                'ordering': ['placa'],
            },
        ),
    ]
